15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
15-02-2023 12:23:26 : ERROR : run : 190 : (Process Details : (17616, SpawnPoolWorker-5), Thread Details : (27704, MainThread))\nLog : 12034345
Traceback (most recent call last):
  File "c:\Users\18123\OneDrive\Documents\sej2020\Machine-Learning-Project\AutoML\ScikitLearn\parSim_v5\utils_backup.py", line 184, in run
    calculated = metric_help[k][2](test_labels, y_pred)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\metrics\_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 919, in check_array
    _assert_all_finite(
  File "C:\Users\18123\anaconda3\envs\research\lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
